// Generated by CoffeeScript 1.9.3
(function() {
  var handleInternalLinks, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  handleInternalLinks = function(container, callback) {
    var containerLinks, handleInternalAnchorClicks, isLocalPath, linkHasInternalAttribute, setInternalLinkAttribute;
    containerLinks = container.getElementsByTagName("a");
    linkHasInternalAttribute = function(link) {
      return link.hasAttribute("internal");
    };
    isLocalPath = function(path) {
      var regexMatch;
      regexMatch = new RegExp(location.host);
      return path.match(regexMatch);
    };
    setInternalLinkAttribute = function(links) {
      var i, len, link;
      for (i = 0, len = links.length; i < len; i++) {
        link = links[i];
        if (isLocalPath(link.href)) {
          link.setAttribute("internal", "");
        }
      }
      return links;
    };
    handleInternalAnchorClicks = function(event) {
      var target;
      target = event.target;
      if (target.tagName === "A" && linkHasInternalAttribute(target)) {
        return callback(event);
      }
    };
    (function(container, links) {
      setInternalLinkAttribute(links);
      return container.addEventListener("click", handleInternalAnchorClicks);
    })(container, containerLinks);
    return {
      refreshLinks: function() {
        return setInternalLinkAttribute(containerLinks);
      },
      currentLinks: function() {
        return [].slice.call(containerLinks);
      }
    };
  };

  root.handleInternalLinks = handleInternalLinks;

}).call(this);
